baseurl: 'https://blog.florentdelannoy.com/'
languageCode: en-uk
title: Florent's Blog
theme: hugo-strata-theme
googleAnalytics: ''
paginate: 10
pygmentsCodeFences: true
pygmentsUseClasses: true
params:
  name: Florent Delannoy
  description: Florent Delannoy's blog
  date_format: '2006-01-02'
  custom_js: []
  custom_css:
  - syntax.css
  - overrides.css
  sidebar:
    avatar: florent.jpg
    bio: >-
      **I'm Florent**, a software engineer
      <br> based in London
    twitter: ''
    github: 'pluies'
    dribbble: ''
    facebook: ''
    googleplus: ''
    flickr: ''
    linkedin: 'florentdelannoy'
    copyright:
      - '&copy; Florent Delannoy'
      - 'Design: [HTML5 UP](//html5up.net)'
  about:
    hide: false
    title: // TODO Come up with witty tagline
    content: >-
      Hi! I'm Florent Delannoy, a software engineer with a focus in devops, cloud-native infrastructure,
      and backend engineering in general. <br>
  portfolio:
    hide: false
    title: Projects
    gallery:
      - image: octocat.jpg
        thumb: octocat.jpg
        title: "[Zeitgeist](https://github.com/Pluies/zeitgeist)"
        description: The language-agnostic dependency checker.
      - image: k8s.png
        thumb: k8s.png
        title: "[k8s setup](https://github.com/Pluies/k8s)"
        description: The infrastructure that runs this blog.
      - image: remaildr.png
        thumb: remaildr.png
        title: "[Remaildr](http://remaildr.com)"
        description: Low-tech, email-based reminders.
      - image: octocat.jpg
        thumb: octocat.jpg
        title: "[Github](https://github.com/Pluies/)"
        description: Open-source bits and bobs.
  contact:
    email: ~
    hide: true
    title: Get In Touch
    content: >-
      Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna.
      Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem
      neque lorem ipsum dolor.
    address:
      - 1234 Somewhere Rd.
      - 'Nashville, TN 00000'
      - United States
    phone: 000-000-0000
    form:
      name: Name
      email: Email
      message: Message
      submit: Send message
menu:
  main:
    - name: Home
      url: /
      weight: 0
    - name: Blog
      url: post/
      weight: 10
